blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/SynkraAI/aiox-core/tree/main/docs
    about: Check our documentation before opening an issue
  - name: Discussions
    url: https://github.com/SynkraAI/aiox-core/discussions
    about: Ask questions and share ideas in Discussions
